apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cache-poc.fullname" . }}-db
  labels:
    {{- include "cache-poc.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
  database: {{ .Values.postgres.database | quote }}
